### ISSUE TITLE
[Small size] Fix search bar , menu position and padding.

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/docs.ubuntu.com#60] opened 2017-04-05 10:22 UTC
The layout of documentation page doesn't look very tidy.
Here a list of things I would like to be fixed:
1. Searching results page , the top search bar should stay full width (also give 10 px of padding between logo + search bar)
![docs-1](https://cloud.githubusercontent.com/assets/21334617/24701238/96d225dc-19f1-11e7-9251-19471404bb8a.jpg)

2. Menu always positioned on the top-right side of the screen, across the different pages (if the title is too long, break it in two lines)
![docs-2](https://cloud.githubusercontent.com/assets/21334617/24701248/a154b452-19f1-11e7-8a20-9d3c19169875.jpg)

3. Core should be replaced by the original logo: https://assets.ubuntu.com/v1/5051e6e5-core_logo.svg

**Comment by nottrobin** [comment] 2017-09-13 17:13
The first two points have been done.

As regards the logo, the problem is that the text in the default "Core" logo clashes with any in-browser text directly next to it, which is why we've used the logo without the text.

This may be addressed down the line if we redesign how the header works, but for now I'm closing this issue.

**Closed by nottrobin** 2017-09-13 17:13 UTC
Labels: Priority: Medium, Type: Bug
