### ISSUE TITLE
Could not build docs (May 24, 2017)

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/docs.ubuntu.com#73] opened 2017-05-24 18:16 UTC
https://juju-stats.admin.canonical.com/index/prodstack-comms/ubuntu-docs-ps45/mojo/2017-05-24-autodeploy.log

End:

```
DISK CRITICAL - free space: / 1 GB (13% inode=62%);| /=8GB;6;7;0;9
2017-05-24 17:56:28 [INFO] 8 OK on webapp/1
2017-05-24 17:56:28 [ERROR] 1 FAIL on webapp/1:
+ /usr/lib/nagios/plugins/check_disk -u GB -w 25% -c 20% -K 5% -p /
DISK CRITICAL - free space: / 1 GB (13% inode=62%);| /=8GB;6;7;0;9
2017-05-24 17:56:28 [WARNING] nagios-check failed (attempt 4 of 6); sleeping for 15s
2017-05-24 17:56:43 [INFO] Retrying (attempt 5 of 6)
2017-05-24 17:56:45 [INFO] 10 OK on haproxy/1
2017-05-24 17:56:47 [INFO] 10 OK on haproxy/0
2017-05-24 17:56:54 [INFO] 8 OK on ubuntu-basenode/0
2017-05-24 17:56:56 [INFO] 8 OK on webapp/0
2017-05-24 17:56:56 [ERROR] 1 FAIL on webapp/0:
+ /usr/lib/nagios/plugins/check_disk -u GB -w 25% -c 20% -K 5% -p /
DISK CRITICAL - free space: / 1 GB (13% inode=62%);| /=8GB;6;7;0;9
2017-05-24 17:56:57 [INFO] 8 OK on webapp/1
2017-05-24 17:56:57 [ERROR] 1 FAIL on webapp/1:
+ /usr/lib/nagios/plugins/check_disk -u GB -w 25% -c 20% -K 5% -p /
DISK CRITICAL - free space: / 1 GB (13% inode=62%);| /=8GB;6;7;0;9
2017-05-24 17:56:57 [WARNING] nagios-check failed (attempt 5 of 6); sleeping for 15s
2017-05-24 17:57:12 [INFO] Retrying (attempt 6 of 6)
2017-05-24 17:57:20 [INFO] 10 OK on haproxy/1
2017-05-24 17:57:21 [INFO] 10 OK on haproxy/0
2017-05-24 17:57:23 [INFO] 8 OK on ubuntu-basenode/0
2017-05-24 17:57:24 [INFO] 8 OK on webapp/0
2017-05-24 17:57:24 [ERROR] 1 FAIL on webapp/0:
+ /usr/lib/nagios/plugins/check_disk -u GB -w 25% -c 20% -K 5% -p /
DISK CRITICAL - free space: / 1 GB (13% inode=62%);| /=8GB;6;7;0;9
2017-05-24 17:57:26 [INFO] 8 OK on webapp/1
2017-05-24 17:57:26 [ERROR] 1 FAIL on webapp/1:
+ /usr/lib/nagios/plugins/check_disk -u GB -w 25% -c 20% -K 5% -p /
DISK CRITICAL - free space: / 1 GB (13% inode=62%);| /=8GB;6;7;0;9
2017-05-24 17:57:26 [ERROR] Nagios checks failed

**Comment by nottrobin** [comment] 2017-06-12 12:05
Duplicate of #75

**Closed by nottrobin** 2017-06-12 12:05 UTC
